[mgr]
# 隠しファイルの表示
show_hidden = true
# 更新日時の表示
linemode = "mtime_only"

[opener]
edit = [{ run = "nvim %*", block = true }]

[[plugin.prepend_fetchers]]
id = "git"
url = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
url = "*/"
run = "git"
