runtime ./options.vim
runtime ./keymap.vim
runtime ./plug.vim
runtime ./colorscheme.vim
runtime ./lspconfig.vim
runtime ./cmp.vim
runtime ./treesitter.vim
runtime ./lspsaga.vim
runtime ./trouble.vim
runtime ./lightline.vim
runtime ./autocmd.vim
