# prompt
#PS1='\[\033[32m\]\u@\h\] \[033[35m\t\] \w]\n\$\[\033[0m\] '
# PS1='\e[32m\u@\h \e[35m\t \e[34m\w \e[0m\$ '
#PS1='\[\033[32m\]\h: \t \w\n\$[\033[0m\] '
#PS1="\[\033[1;32m\]\$(date +%Y/%m/%d_%H:%M:%S)\[\033[0m\] \[\033[33m\]\H:\w\n\[\033[0m\][\u@ \W]\[\033[36m\]\$(__git_ps1)\[\033[00m\]\$ "
PS1='\[\033[33m\]\u \[\033[32m\t\] \[\033[34m\w\]\n\[\033[0m\]\$ '
# alias
alias ls='exa'
alias la='exa -a'
alias ll='exa -alh'
alias cat='bat'
alias mkdir='mkdir -p'
alias df='df -h'
